[Lumi]
2016APV = 19520.0
2016 = 16810.0
2017 = 41480.0
2018 = 59830.0
Unit = "pb-1"

[Global]
ScalefactorError = 0.026

[DYJetsToLL_M-50_13TeV_AM]
XSec = 6104.0
FilterEff = 1.0
kFactor = 0.944
XSecOrder = "NLO"
ProcessGroup = "DrellYan"
das_name_2016APV = ["/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM"]
das_name_2016 = ["/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM"]
das_name_2017 = ["/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM"]
das_name_2018 = ["/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/NANOAODSIM"]