output = "outputs"
is_data = false
year = "2018"
era = "_"
process = "WminusH_HToBB_WToQQ_M-125_13TeV_PH"
dataset = "/WminusH_HToBB_WToQQ_M-125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"
is_crab_job = true
input_files = ["__dummy__"]