output = "outputs"
is_data = true
year = "2018"
era = "D"
process = "EGamma_13TeV_2018_D"
dataset = "/EGamma/Run2018D-UL2018_MiniAODv2_NanoAODv9-v3/NANOAOD"
is_crab_job = false
input_files = []
generator_filter_key = ""