output = "outputs"
is_data = false
year = "2018"
era = "_"
process = "DYJetsToLL_LHEFilterPtZ-100To250_MatchEWPDG20_13TeV_AM"
dataset = "/DYJetsToLL_LHEFilterPtZ-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"
is_crab_job = true
input_files = ["__dummy__"]