output = "outputs"
is_data = true
year = "2018"
era = "D"
process = "JetHT_13TeV_2018_D"
dataset = "/JetHT/Run2018D-UL2018_MiniAODv2_NanoAODv9-v2/NANOAOD"
is_crab_job = false
input_files = []
generator_filter_key = ""