
[WWTo2L2Nu_13TeV_PH]
XSec = 10.48
FilterEff = 1.0
kFactor = 1.162
XSecOrder = "NNLO"
ProcessGroup = "WW"
generator_filter_key = "ww_mLL_less_200"
is_data = false
das_name_2016 = ["/WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM"]
das_name_2017 = ["/WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM"]
das_name_2016APV = ["/WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM"]
das_name_2018 = ["/WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2/NANOAODSIM"]