[QCD_Pt_15to30_13TeV_P8]
XSec = 1837410000
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_15to30_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_30to50_13TeV_P8]
XSec = 140932000
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_30to50_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_50to80_13TeV_P8]
XSec = 19204300
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_50to80_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_80to120_13TeV_P8]
XSec = 2762530
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_80to120_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_120to170_13TeV_P8]
XSec = 471100
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_120to170_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_170to300_13TeV_P8]
XSec = 103300
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_170to300_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_300to470_13TeV_P8]
XSec = 7823
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_300to470_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_470to600_13TeV_P8]
XSec = 648.2
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_470to600_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_600to800_13TeV_P8]
XSec = 186.9
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_600to800_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_800to1000_13TeV_P8]
XSec = 32.293
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_1000to1400_13TeV_P8]
XSec = 9.4183
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_1400to1800_13TeV_P8]
XSec = 0.84265
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_1800to2400_13TeV_P8]
XSec = 0.114943
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_2400to3200_13TeV_P8]
XSec = 0.00682981
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]

[QCD_Pt_3200toInf_13TeV_P8]
XSec = 0.000165445
FilterEff = 1.0
kFactor = 1.0
XSecOrder = "LO"
ProcessGroup = "QCD"
is_data = false
das_name_2018 = ["/QCD_Pt_3200toInf_TuneCP5_13TeV_pythia8/RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1/NANOAODSIM"]
