output = 'test_data_2017'
is_data = true                                    # Is Data?
x_section_file = '$MUSIC_BASE/configs/xsections_and_lumi/x_sections.toml'
year = '2017'
process = 'SingleMuonX_2017'
dataset = '/SingleMuonX/bar/abc/NANOAOD'
s_crab_job = false


input_files = [
    '/home/home1/institut_3a/silva/projects/music/test_data/SingleMuon2017/037CED2F-27B3-DB4A-9A9D-C588589EDCE7.root',
    # '/home/home1/institut_3a/silva/projects/music/test_data/SingleMuon2017/056C66FC-4143-4546-9861-D089AFFB4E55.root',
]

# input_files = [
#     'root://xrootd-cms.infn.it///store/data/Run2017C/SingleMuon/NANOAOD/UL2017_MiniAODv2_NanoAODv9-v1/120000/037CED2F-27B3-DB4A-9A9D-C588589EDCE7.root',
#     'root://xrootd-cms.infn.it///store/data/Run2017C/SingleMuon/NANOAOD/UL2017_MiniAODv2_NanoAODv9-v1/120000/056C66FC-4143-4546-9861-D089AFFB4E55.root',
# ]


# input_files = [
#     'root://cms-xrd-global.cern.ch///store/data/Run2017C/SingleMuon/NANOAOD/UL2017_MiniAODv2_NanoAODv9-v1/120000/037CED2F-27B3-DB4A-9A9D-C588589EDCE7.root',
#     'root://cms-xrd-global.cern.ch///store/data/Run2017C/SingleMuon/NANOAOD/UL2017_MiniAODv2_NanoAODv9-v1/120000/056C66FC-4143-4546-9861-D089AFFB4E55.root',
# ]
