output = 'test_mc_2018'
is_data = false                                    # Is Data?
x_section_file = '$MUSIC_BASE/configs/xsections_and_lumi/x_sections.toml'
year = '2018'
process = 'DYJetsToLL_M-50_13TeV_AM'
dataset = '/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM'
is_crab_job = false

input_files = [
    '/home/home1/institut_3a/silva/projects/music/test_data/DY2018/f01.root',
    ]

