output = 'test_mc_2018_TTToSemiLeptonic_2018'
is_data = false                                    # Is Data?
x_section_file = '$MUSIC_BASE/configs/xsections_and_lumi/x_sections.toml'
year = '2018'
process = 'TTToSemiLeptonic_2018'
dataset = '/TTToSemiLeptonic_2018/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM'
is_crab_job = false

input_files = [
    '/disk1/silva/projects/NanoMUSiC_Test_Data/TTToSemiLeptonic_2018/f01.root',
    ]

