output = 'test_data_2018'
is_data = true                                    # Is Data?
x_section_file = '$MUSIC_BASE/configs/xsections_and_lumi/x_sections.toml'
year = '2018'
era = 'C'
process = 'SingleMuonX_2017'
dataset = '/SingleMuonX/bar/abc/NANOAOD'
is_crab_job = false

input_files = [
    '/disk1/silva/projects/NanoMUSiC_Test_Data/SingleMuon2018/f01.root',
]