output = 'test_mc_2017'
is_data = false                                    # Is Data?
x_section_file = '$MUSIC_BASE/configs/xsections_and_lumi/x_sections.toml'
year = '2017'
era = 'C'
process = 'DYJetsToLL_M-50_13TeV_AM'
dataset = '/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM'
is_crab_job = false

input_files = [
    '/disk1/silva/projects/NanoMUSiC_Test_Data/DY2017/f01.root',
#     '/disk1/silva/projects/NanoMUSiC_Test_Data/DY2017/f02.root',
#     '/disk1/silva/projects/NanoMUSiC_Test_Data/DY2017/f03.root',
    ]


# input_files = [
#     'root://cms-xrd-global.cern.ch///store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v2/100000/04426F83-BF53-0440-B2D1-F2DD9AB96EB8.root',
#     'root://cms-xrd-global.cern.ch///store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v2/100000/04620FA2-DB18-7F4A-B30C-BAFD1C5B673D.root',
#     'root://cms-xrd-global.cern.ch///store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v2/230000/A295E63F-D6E2-B744-9A83-ACE9D7DF5791.root',
# ]

