output = 'test_mc_2016APV_DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8'
is_data = false                                    # Is Data?
# x_section_file = '$MUSIC_BASE/configs/xsections_and_lumi/x_sections.toml'
year = '2016APV'
era = 'C'
process = 'DYJetsToLL_M-50_13TeV_AM'
dataset = '/ZToMuMu_M-1400To2300_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM'
is_crab_job = false


input_files = [
    'root://cms-xrd-global.cern.ch///store/mc/RunIISummer20UL16NanoAODAPVv9/ZToMuMu_M-1400To2300_TuneCP5_13TeV-powheg-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_preVFP_v11-v1/270000/2F76BC39-0483-704F-95AD-57FC63A6EA4E.root',
    ]
