output = 'test_mc_2017_ZGTo2NuG_TuneCP5_13TeV-amcatnloFXFX-pythia8'
is_data = false                                    # Is Data?
# x_section_file = '$MUSIC_BASE/configs/xsections_and_lumi/x_sections.toml'
year = '2017'
era = 'C'
process = 'DYJetsToLL_M-50_13TeV_AM'
dataset = '/ZGTo2NuG_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM'
is_crab_job = false

input_files = [
    'root://madhatter.csc.fi:1094/pnfs/csc.fi/data/cms/store/mc/RunIISummer20UL17NanoAODv9/ZGTo2NuG_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v1/60000/57039DF6-DC5C-9B4F-82A7-9C2B51EC72C8.root',
    ]



