[DYJetsToLL_M-50_13TeV_AM]
is_data = false
samples_2016APV = ["/foo/bar/NANOAODSIM", "/foo/bar/NANOAODSIM", ]
samples_2016 = ["/foo/bar/NANOAODSIM", "/foo/bar/NANOAODSIM", ]
samples_2017 = ["/foo/bar/NANOAODSIM", "/foo/bar/NANOAODSIM", ]
samples_2018 = ["/foo/bar/NANOAODSIM", "/foo/bar/NANOAODSIM", ]
x_section = 6104.0
filter_efficiency = 1.0
k_factor = 0.944
generator = "FOO"
x_section_order = "NLO"
process_group = "DrellYan"