### This script allows, in your plot, to aggregate more samples in one sample group (more convinient for High Energy Physics and CMS notation)
class AggregationGroupMixin(object):

    @classmethod
    def get_aggregation_groups(cls):
        """ Reimplementation of parent class in ectools with HEP groups

        """
        groups = {}
        #no aggregation and no pre-defined group. Every sample will be plotted
        groups["process"]={}
        # no aggregation (for debug)
        groups["none"] = {}
        
        
        # some aggregation (default)
        groups["medium"] = {
                            "TTW": "TTbarV",
                            "TTZ": "TTbarV",
                            "TTG": "TTbarV",
                            "TTGG": "TTbarV",
                            "WW": "DiBoson",
                            "ZZ": "DiBoson",
                            "WZ": "DiBoson",
                            "WWW": "TriBoson",
                            "WWZ": "TriBoson",
                            "WZZ": "TriBoson",
                            "ZZZ": "TriBoson",
                            "WWG": "TriBoson",
                            "WGG": "TriBoson",
                            "WZG": "TriBoson",
                            "BlackHole*": "BlackHole Signal",
                            "SeesawTypeIII*": "Seesaw Signal",
                            "QBHToEMu*": "QBH Signal",
                            "RPVresonantToEMu*": "RPV Signal",
                            "WprimeToTB*": "W' Signal",
                            "ZToInvisible": "DrellYan",
                            "ZToQQ": "DrellYan",
                            "TTbarTTbar": "TTTT"}

        # a lot aggregation (for public plots)
        groups["strong"] = {
                            "TTW": "TTbar",
                            "TTZ": "TTbar",
                            "TTbar_13TeV_P8": "TTbar",
                            "WW": "Multi-Boson",
                            "WW_13TeV_P8": "Multi-Boson",
                            "ZZ": "Multi-Boson",
                            "ZZ_13TeV_P8": "Multi-Boson",
                            "WZ": "Multi-Boson",
                            "WZ_13TeV_P8": "Multi-Boson",
                            "WG": "Multi-Boson",
                            "DiPhoton": "Multi-Boson",
                            "GG": "Multi-Boson",
                            "WWW": "Multi-Boson",
                            "WWZ": "Multi-Boson",
                            "WZZ": "Multi-Boson",
                            "ZZZ": "Multi-Boson",
                            "WWG": "Multi-Boson",
                            "WGG": "Multi-Boson",
                            "WZG": "Multi-Boson",
                            "ZG": "Multi-Boson",
                            "ttHJetToNonbb_M125_13TeV_AM": "HIG",
                            "ttHJetTobb_M125_13TeV_AM": "HIG",
                            "BlackHole*": "Signal",
                            "SeesawTypeIII*": "Signal",
                            "QBHToEMu*": "Signal",
                            "RPVresonantToEMu*": "Signal",
                            "WprimeToTB*": "Signal",
                            "Di-Boson": "Multi-Boson",
                            "ZToInvisible": "DrellYan",
                            "ZToInvis": "DrellYan",
                            "ZToQQ": "DrellYan",
                            "TTbarTTbar": "TTbar",
                            "TTG": "TTbar",
                            "TTGG": "TTbar",
                            "TG": "Top",
                            "tG": "Top",
                            "tG": "Top",
                            "TZQ": "Top",
                            "tZQ": "Top"}

        #customDY. Only DY samples are NOT grouped (for public plots)
        groups["customDY"] = {
            'ZTo*' : 'DrellYanZTo',
            #'DrellYan*' : 'DrellYan' ,
            #'DY*' : 'DrellYan',
            "DYJetsToLL_Pt*" : "DYJetsToLL_Pt",
            'ZJetsToNuNu*' :  'ZToInvisible',
            'WTo*' : 'W', 
            'WJets*' : 'W',
            'GJets*' : 'Gamma',
            'WZTo*' : 'WZ',
            'WGTo*' : 'WG',
            'WGJets*' : 'WG',
            'WWTo*' : 'WW',
            'ZZTo*' : 'ZZ',
            'ZGTo*' : 'ZG',
            'GG_*' : 'GG', 
            'GGJets_*' : 'GG', 
            'DiPhotonJets*' : 'GG',
            'ZZZ_*' : 'ZZZ',
            'WWW_*' : 'WWW',
            'WWG_*' : 'WWG',
            'WWZ_*' : 'WWZ',
            'WGG_*' : 'WGG',
            'WZG_*' : 'WZG',
            'WZZ_*' : 'WZZ',
            'TTWJets*' : 'TTW',
            'TTGJets*' :  'TTG',
            'TTZTo*' : 'TTZ',
            'TTGG_0Jets*' : 'TTGG', 
            'ST_*-channel*' : "Top",
            'ST_tW_*' : "Top",
            'TT_*' : "TTbar",
            'TTTo*' : 'TTbar',
            "TTW": "TTbar",
            "TTZ": "TTbar",
            "TTbar_13TeV_P8": "TTbar",
            "WW": "Multi-Boson",
            "WW_13TeV_P8": "Multi-Boson",
            "ZZ": "Multi-Boson",
            "ZZ_13TeV_P8": "Multi-Boson",
            "WZ": "Multi-Boson",
            "WZ_13TeV_P8": "Multi-Boson",
            "WG": "Multi-Boson",
            "DiPhoton": "Multi-Boson",
            "GG": "Multi-Boson",
            "WWW": "Multi-Boson",
            "WWZ": "Multi-Boson",
            "WZZ": "Multi-Boson",
            "ZZZ": "Multi-Boson",
            "WWG": "Multi-Boson",
            "WGG": "Multi-Boson",
            "WZG": "Multi-Boson",
            "ZG": "Multi-Boson",
            "ttHJetToNonbb_M125_13TeV_AM": "HIG",
            "ttHJetTobb_M125_13TeV_AM": "HIG",
            "BlackHole*": "Signal",
            "SeesawTypeIII*": "Signal",
            "QBHToEMu*": "Signal",
            "RPVresonantToEMu*": "Signal",
            "WprimeToTB*": "Signal",
            "Di-Boson": "Multi-Boson",
            "ZToInvisible": "DrellYan",
            "ZToInvis": "DrellYan",
            "ZToQQ": "DrellYan",
            "TTbarTTbar": "TTbar",
            "TTG": "TTbar",
            "TTGG": "TTbar",
            "TG": "Top",
            "tG": "Top",
            "tG": "Top",
            "TZQ": "Top",
            "tZQ": "Top",
            "TGJet": "Top",
            'GluGluHTo*' : 'HIG',
            'VBFHTo*' : 'HIG', 
            'VBF_HTo*' : 'HIG',
            'VHTo*' : 'HIG', 
            'WplusH_HTo*' : 'HIG',
            'WminusH_HTo*' : 'HIG',
            'ZH_HTo*' : 'HIG', 
            'ggZH_HTo*' : 'HIG', 
            'ttHTo*' : 'HIG', 
            'QCD_*' : "QCD",
}


        #customWJ. Only WJ samples are NOT grouped (for public plots)
        groups["customWJ"] = {
            'ZTo*' : 'DrellYanZTo',
            'DrellYan*' : 'DrellYan' ,
            'DY*' : 'DrellYan',
            #"DYJetsToLL_Pt*" : "DYJetsToLL_Pt",
            'ZJetsToNuNu*' :  'ZToInvisible',
            'WTo*' : 'WToLNu_Mb', 
            #'WJets*' : 'W',
            'GJets*' : 'Gamma',
            'WZTo*' : 'WZ',
            'WGTo*' : 'WG',
            'WGJets*' : 'WG',
            'WWTo*' : 'WW',
            'ZZTo*' : 'ZZ',
            'ZGTo*' : 'ZG',
            'GG_*' : 'GG', 
            'GGJets_*' : 'GG', 
            'DiPhotonJets*' : 'GG',
            'ZZZ_*' : 'ZZZ',
            'WWW_*' : 'Multi-Boson',
            'WWG_*' : 'Multi-Boson',
            'WWZ_*' : 'Multi-Boson',
            'WGG_*' : 'Multi-Boson',
            'WZG_*' : 'Multi-Boson',
            'WZZ_*' : 'Multi-Boson',
            'TTWJets*' : 'TTW',
            'TTGJets*' :  'TTG',
            'TTZTo*' : 'TTZ',
            'TTGG_0Jets*' : 'TTGG', 
            'ST_*-channel*' : "Top",
            'ST_tW_*' : "Top",
            'TT_*' : "TTbar",
            'TTTo*' : 'TTbar',
            "TTW": "TTbar",
            "TTZ": "TTbar",
            "tt*" : "TTbar",
            "TTbar_13TeV_P8": "TTbar",
            "WW": "Multi-Boson",
            "WW_13TeV_P8": "Multi-Boson",
            "WZ*" : "Multi-Boson",
            "ZZ": "Multi-Boson",
            "ZZ_13TeV_P8": "Multi-Boson",
            "WZ": "Multi-Boson",
            "WZ_13TeV_P8": "Multi-Boson",
            "WG": "Multi-Boson",
            "DiPhoton": "Multi-Boson",
            "GG": "Multi-Boson",
            "WWW": "Multi-Boson",
            "WWZ": "Multi-Boson",
            "WZZ": "Multi-Boson",
            "ZZZ": "Multi-Boson",
            "WWG": "Multi-Boson",
            "WGG": "Multi-Boson",
            "WZG": "Multi-Boson",
            "ZG*": "Multi-Boson",
            "ttHJetToNonbb_M125_13TeV_AM": "HIG",
            "ttHJetTobb_M125_13TeV_AM": "HIG",
            "BlackHole*": "Signal",
            "SeesawTypeIII*": "Signal",
            "QBHToEMu*": "Signal",
            "RPVresonantToEMu*": "Signal",
            "WprimeToTB*": "Signal",
            "Di-Boson": "Multi-Boson",
            "ZToInvisible": "DrellYan",
            "ZToInvis": "DrellYan",
            "ZToQQ": "DrellYan",
            "TTbarTTbar": "TTbar",
            "TTG": "TTbar",
            "TTGG": "TTbar",
            "TG": "Top",
            "tG": "Top",
            "tG": "Top",
            "TZQ": "Top",
            "tZQ": "Top",
            "TGJet": "Top",
            "TGJet*" : "Top",
            'GluGluHTo*' : 'HIG',
            'VBFHTo*' : 'HIG', 
            'VBF_HTo*' : 'HIG',
            'VHTo*' : 'HIG', 
            'WplusH_HTo*' : 'HIG',
            'WminusH_HTo*' : 'HIG',
            'ZH_HTo*' : 'HIG', 
            'ggZH_HTo*' : 'HIG', 
            'ttHTo*' : 'HIG', 
            'QCD_*' : "QCD",
}



        # for testing
        groups["testing"] = {}
        for i in range(9):
            groups["testing"]["proc%d" % i] = "proc%d" % i
        return groups
