#!/bin/bash
if [ $(uname -i) != x86_64 ]; then
    echo "Machine platform is $(uname -i), which is not x86_64"
    echo "CRAB >= 2.7 needs 64bit UI. Please log in to lx64ui."
    exit 1
fi

source /afs/cern.ch/cms/LCG/LCG-2/UI/cms_ui_env_3_2.sh
source /afs/cern.ch/cms/ccs/wm/scripts/Crab/crab.sh
#source /afs/cern.ch/cms/ccs/wm/scripts/Crab/CRAB_2_11_1_pre3/crab.sh
echo Using CRAB: $(which crab)
music_crab.py $*
