# Our workflow will define to stages: build and deploy the web site
# These stages will be attached to jobs and define the sequence in which they will be executed
#
# This example shows how to build doxygen documentation and deploy it to a DFS website.

stages:
  - build
  - deploy

# Example job to build doxygen documenation with gitlab. Copy and adapt to your specifc case.
# By default it is commented out to not collide with the other build stages.
# Heavily based on: https://gitlab.com/pages/doxygen/
doxygen:
  stage: build
  # The centrally provided worker has doxygen installed
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  script:
    # Prepare the documentation
    - doxygen tools3a_doxy_cfg
    # Copy the generated web to the local public/ directory
    - mv doc/html/ public/
  # Upload the public/ directory as artifact. The web generated will be attached to the build
  artifacts:
    paths:
      - public


# Deploy the pages generated to DFS
dfsdeploy:
  # Executed during the deploy stage
  stage: deploy
  # Only when the master branch is pushed
  only:
    - master
  # Custom docker image providing the needed tools to deploy in DFS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
  # Script that performs the deploy to DFS. Makes use of the variables defined in the project
  # It will not sync the generated content with the folder in DFS (risk of deleting DFS management files)
  # It will just override the contents of DFS or copy new files
  - deploy-dfs
