name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          additional-packages: font-fira-code
          working-directory: 'submodule/'
          doxyfile-path: 'docs/Doxygen'
          enable-latex: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./submodule
